### ISSUE TITLE
Total Commander draw back to side after rename operation

### ISSUE THREAD

**Issue by qijianjun** [fuhsjr00/bug.n#83] opened 2016-03-09 05:00 UTC
Once I rename a file and push `enter`, the tcmd window will draw back to the right side, seems that a new window is left of it, but there is no new window generated.

bug.n version: 0.9.0

**Comment by joten** [comment] 2016-03-09 18:55
Looks like there is a new window. Can you click into the void and get the window information by using <kbd>Win</kbd><kbd>I</kbd> or does the window list (<kbd>Win</kbd><kbd>Shift</kbd><kbd>I</kbd>) give any clues?

**Comment by qijianjun** [comment] 2016-03-10 03:18
@joten Yes. there is a new window.

`win+shift+i`
>Active Window
0x102be:	Total Commander (x64) 8.52a - Steve Lonmo
>Window List
0x462127c:	
0x102be:	Total Commander (x64) 8.52a - Steve Lonmo

`win+i`

>ID: 0x1087c
class:	WorkerW
title:	
process:	explorer.exe [2680]
style:	0x96000000
metrics:	x: 0, y: 0, width: 1600, height: 900
tags:	
>
>Config_rule=WorkerW;;;0;;;;;0;

**Comment by joten** [comment] 2016-04-09 09:15
I could not reproduce the issue reliably. One time I observed the behaviour you described, but most times I could see a window almost unvisibly opening and immediately closing again; bug.n reacted by resetting the layout leaving no gap.

A bit of debugging showed the following window to appear and be recognized as a popup:
`2016-04-09 11:03:21 DEBUG[1] Manager_applyRules: class: TDLG2FILEACTIONMIN, title: Total Commander, wndId: 0x405b2, rule #: 1`

I will have to re-implement `Config_shellMsgDelay` in the right place to allow some delay in the reaction of bug.n to shell messages.

**Comment by joten** [comment] 2016-05-08 16:43
This issue should be solved.

**Closed by joten** 2016-05-08 16:43 UTC
