### ISSUE TITLE
Doesn't work on 4k screen with 150% scaling

### ISSUE THREAD

**Issue by waltframe** [fuhsjr00/bug.n#18] opened 2014-12-30 17:45 UTC
Hi, i have a 3840x2160 monitor with windows 7 running with 150% scaling and only seems to use roughly half of the screen, it never maximizes windows larger than what looks like 2400x1500 in the upper left corner.

**Comment by joten** [comment] 2015-01-02 12:30
It looks like this is related to issue #16.

* Which version of bug.n do you use?
* If you use the development version, since when does the probplem occur? Since 13.12.2014?

I will need some time to reproduce the problem, since I do not have a test system readily available.

**Comment by joten** [comment] 2015-01-13 12:18
Any new information?

**Comment by joten** [comment] 2015-01-16 20:44
I would like to close this one; it seems, there is no new information to go on, and I could not reproduce the bug.

**Closed** 2015-01-24 11:06 UTC
