### ISSUE TITLE
Unusable in Windows 8.1? :^(

### ISSUE THREAD

**Issue by Chadehoc** [fuhsjr00/bug.n#49] opened 2015-05-14 23:35 UTC
I was very happy with bug.n on Win7 at work. I had to install Win8.1 at home, so bug.n was one of the first thing I installed, and it behaves very badly.  :^(
* "Windows-look" menus don't work, like Firefox or Wordpad menus: nothing pops up. Standard menus (as in Notepad++) work.
* All popups appear very high, only the bottom of the window can be shown, I have to use #+s to move it down.
* Windows made floating seem fairly out of control, regularly resizing or moving at whim.
* When I leave bug.n, the current windows (e.g. Firefox) disappear. I have monitors of different sizes, and when brought to the taller one, the top of the windows is visible, and the remainder is "behind the wallpaper". Also, when toying with the taskbar, the hidden windows can sometime show its title bar dimly, as in transparency but unclickable. Even (still having left bug.n) when closing (via the taskbar) and running again the app, it appears behind the desktop again.  I have to leave the session to get things back in order.

Has anyone succeeded in having bug.n work in Win 8.1?

**Comment by louy2** [comment] 2015-05-18 00:11
I am using bug.n happily in Win 8.1, but I have to admit I don't use it your way. 

- What do you mean by "Windows-look" menu? My firefox seems alright.
- My popups has either been configured to not be managed, or poped up as main windows or maximized windows depending on my mode.
- Windows 8.1 indeed has made floating window out of control, I just don't use floating much.
- Exit bug.n and I get all my windows back. I only use the built-in monitor of my laptop though.

**Comment by Chadehoc** [comment] 2015-05-18 20:02
> What do you mean by "Windows-look" menu? My firefox seems alright.

I meant, there are "classical" menus with a menu bar, textual entries, and drop-down menu lists, vs. more customised menus like Firefox' single menu with icons, etc. The formers are ok, the latters not (I had tried several applications, I don't remember which exactly).

> My popups has either been configured to not be managed, or poped up as main windows or maximized windows depending on my mode.
> Windows 8.1 indeed has made floating window out of control, I just don't use floating much.

I prefer floating to not managed at all. When something turns bad I first try to float, and eventually to unmanage (chiefly the windows that seem to be hidden/shown programmatically from others). I'll try to unmanage every one that I used to float.

> Exit bug.n and I get all my windows back. I only use the built-in monitor of my laptop though.

I use two monitors with very different resolutions. I wonder if that could be the difference.

**Comment by joten** [comment] 2015-07-08 19:20
Do the issues still persist?

Currently, I am not using Windows. But before I used Windows 8.1 since its inception -- though on a notebook with just the built-in screen. I did, of course, test the multi-monitor support of bug.n -- though (again) not with two 'external' monitors, just one and the built-in one. Firefox, especially with its preferences menu: no problem. All behaves ore or less like on Windows 7

Did you test your system with the default configuration of bug.n, i. e. no `Config.ini`?

**Comment by joten** [comment] 2015-07-08 19:21
Wrong button!

**Comment by Chadehoc** [comment] 2015-07-08 22:07
> Did you test your system with the default configuration of bug.n, i. e. no `Config.ini`?

Well, it works **much** better! The config that is still fine in W7 does something wrong in W8.1, I have still to find what line(s) are responsible, then I hope I can precise this issue better.

**Comment by Chadehoc** [comment] 2015-07-08 22:35
>  I have still to find what line(s) are responsible, then I hope I can precise this issue better.

Strange: the very fact of having a `config.ini` file (even an empty file) triggers the issues I described. Delete or rename it, and it seems to work well (except I don't have my usual shortcuts, and some of the default ones don't play well on a French keyboard, so I didn't check *everything*).

I launch bug.n by `bug.n\src\Main.ahk bug.n` (the bug.n directory as argument), with current directory being `bug.n\src`.

**Comment by willprice** [comment] 2015-07-14 17:53
I'm having the same issues as @Chadehoc, dual monitors being run off a laptop (which I disable the screen on). I'll try and reproduce the stable behaviour without `Config.ini` tomorrow when I have access to my work laptop.

**Comment by jrmrjnck** [comment] 2015-08-13 00:23
I'm also having problems on Windows 8.1 (two external monitors from a laptop), and using defaults (no config.ini) does not fix anything.

Taskbar popups are always in the wrong place - program icon menus are pushed to the right end of the monitor, and the tray popup is pushed onto the other monitor.

Also, sometimes programs will start on the wrong monitor even though space was made in the layout on the correct monitor. Usually shuffling or resizing the window will get it to snap into place.

Bug.n also severely messes up the aero snap functionality. If I try to drag any window from the secondary monitor to the primary (right to left), aero snap is triggered on the left edge of the right (secondary) monitor, and the program gets forced to some small width (1 pixel for chrome) and stuck in between the screens. In fact, dragging any window on primary/left monitor triggers this snap, even if the mouse doesn't cross the boundary. This behavior even persists after quitting bug.n! The only way to reset is to switch which monitor is primary and then switch back.

**Comment by joten** [comment] 2016-01-19 19:36
I sadly cannot reproduce the issue; since reporting the issue I used bug.n on

* Windows 7, dual monitor system
* Windows 7 laptop with an external monitor
* WIndows 10 laptop with an external monitor
* Windows 8/8.1 laptop, sometimes with an external monitor, too
* Windows 10 laptop

Normally I am running bug.n as a script with AutoHotkey 32-bit/utf-8, currently "v1.1.22.09 (Unicaode 32-bit)". Can anyone still reproduce the issue and can state the options used for running bug.n?

**Comment by Chadehoc** [comment] 2016-01-20 11:38
I no longer have 8.1 at home (updated to W10) so I can no longer answer precisely... At the time it was the latest (then) Ahk, 64 bits, launched with the executable by `Main.ahk` directly.

**Comment by jrmrjnck** [comment] 2016-01-24 05:07
I had to stop using bug.n because it was so buggy (which sucks because it's basically the *only* tiling window manager for windows - the competitors have tons of glossy "features" but none of the core keyboard driven usability).

I will try to reproduce with the latest version when I get a chance next week.

**Comment by joten** [comment] 2016-03-09 20:12
Any news on this issue?

**Comment by Chadehoc** [comment] 2016-03-09 22:37
> Any news on this issue?

I switched to W10 long ago, so this is no longer an issue for me at least ! :^)

**Comment by joten** [comment] 2016-04-08 18:45
I am closing this one. I cannot reproduce the problem and with no testing and analysis there is nothing I can do.

**Closed by joten** 2016-04-08 18:45 UTC
Labels: unverified
