### ISSUE TITLE
Chrome new Tab

### ISSUE THREAD

**Issue by DarkDirk** [fuhsjr00/bug.n#22] opened 2015-02-01 12:22 UTC
When I open a few new tabs with Ctrl+t in Chrome, bug.n sometimes detects a new window. This leads to a split in the tiling view with the active region empty.

When I focus a different Window or open a website in the new tab, bug.n detects the mistake and resizes chrome again.

If you need further information please ask :)

**Comment by joten** [comment] 2015-02-01 20:32
On the one hand this sounds like issue #1. Which version of bug.n do you use?

On the other hand, since bug.n _only_ "sometimes detects a new window", it might just be a timing problem. You may add the following line to your `Config.ini` to remedy the problem:
`Config_shellMsgDelay=450` The default value of `Config_shellMsgDelay` is `350`; you may increase the value even more, if needed.

**Comment by morinted** [comment] 2015-02-02 19:49
Even with a shell msg delay of 1000, I still intermittently get this issue on the latest bug.n-dev.exe. I can easily reproduce it by opening Chrome and just tapping Ctrl + T. It happens once every 5 or so tabs.

**Comment by franckspike** [comment] 2015-02-02 19:53
Ctrl + T  gives:

Active Window
0xa053e:	Nouvel onglet - Google Chrome

Window List
0xa00912:	Chrome Legacy Window
0xa053e:	Nouvel onglet - Google Chrome


"Chrome Legacy Window" is the window that has no display.

**Comment by morinted** [comment] 2015-02-02 19:55
Didn't even think to look at that. I'm not sure if Chrome Legacy Window is used for anything else, but I was able to ignore it with this in my Config.ini:

    Config_rule=Chrome_RenderWidgetHostHWND;.*;;0;0;0;0;1;0;

**Comment by joten** [comment] 2015-02-05 19:54
Well, I tried an older version of Chrome in the form of "SRWare Iron version 38.0.2050.0 (295000)" and  "Google Chrome version 40.0.2214.94 m", both on Windows 8.1, but I had no luck reproducing the problem; I also tried some version of Google Chrome on Windows 7 and could observe some glitch at one time, but I hit the next `Ctrl+T` too fast and it went away.

Nevertheless, since you already have done all the work -- BTW thanks -- I will put the additional rule in `Config.ahk`.

**Comment by franckspike** [comment] 2015-02-05 20:06
There are about 3 cases that happens all the time on my win7:
 - closing windows do not always work, the same window closed differently works though
 - sometimes the window activation get crasy, I think this is the #14 issue
 - when windows are set hidden (not by us), I think we should not bring them to visible
 - some child window popups should not be managed

Have you seen my pull request ?
I wonder how we could collaborate, for example if you don't want to include the Server.ahk but still want some of my fixes...  where can we sync'up on this subject ?

**Comment by joten** [comment] 2015-02-12 20:13
> There are about 3 cases that happens all the time on my win7

Are these cases in respect to any window, or in respect to Chrome?

> closing windows do not always work, the same window closed differently works though

Which method is which? `Win+C` vs. `Alt+F4`?

> sometimes the window activation get crasy

Only in a multi-monitor environment?

> when windows are set hidden (not by bug.n), I think we should not bring them to visible

I will look into it.

> some child window popups should not be managed

If they are pop-ups, _bug.n_ should already apply the respective rule: `Config_rule_#2=.*;.*;Window_isPopup;0;0;0;1;1;1;` (with the current development version), which is not to manage them.

> Have you seen my pull request ?

I did see "remote control", "chrome browser rule" and "typo Manager_serCursor" and adopted all of them. Did I miss any?

> I wonder how we could collaborate

The pull requests should work; I think, if you sync your fork and than make a new pull request, it should not be mixed-up with the old one. I would have  pulled your code regarding "chrome browser rule" and "typo Manager_serCursor" one-to-one; only for the "remote control" I saw your code and knew, that almost all was already there. Maybe it would be easier if @fuhsjr00 would add you to the list of contributors, if you are interested in a more direct involvement.

**Comment by franckspike** [comment] 2015-02-12 20:57
The 3 cases are not specific to Chrome.

ProcessExplorer with "hide when minimized" option selected:
Another autohotkey doing SendInput !{F4} to it will not close it (it closes but reappear).
Alt+F4 keyboard hotkey does the same.
Win+c does the same but it reappear behind my other windows (they have transparency) and as soon as I click it pops up as view's main window.
File -> Exit will close the window properly though.

When this option is disabled, closing the window will not try to hide it instead, so bug.n will not bring this hidden window back to visible.

I seems to come down to the "when windows are set hidden (not by bug.n (except win+c)), I think we should not bring them to visible"

Another window that does not close with win+c or alt+F4 is a file deletion confirmation dialog poped up by xplorer2 (a file explorer). Its close button does not work either. This popup must have it parent=NULL because I can perform other tasks on the parent (main) window wil it is open. Maybe it does not match/set Window_isPopup because of this. I'll have a fast look at it.

I am trying to begin to use git rebase instead of git merge to clean up the commit logs, but it is not a good idea since I am working on it at home and at work... I hope future merges with pull requests will not keep the whole history of commits, even before a sync point...

I am interested for more direct involvement, should I write to @fuhsjr00 ?

**Comment by franckspike** [comment] 2015-02-12 21:32
The file explorer deletion popup is not a popup (not WS_POPUP), but another window.
It is shown by another thread of the same process, they also share the same windows proc i'm not sure why though. I think this window should not be seen as a popup then.

But when the its close button triggers a WM_SHOWWINDOW bShow=false, WM_SHOWWINDOW bShow=true is received right after.

Again it looks like the case of the "let explicitely hidden windows hidden"

I wonder if that would have down sides or implementation problems.

If we kept a list of the windows we hide due to view changes, we could know if we could make them back visible or not. There would be a problem with this if any window hidden by a view change also gets explicitely hidden by another process, in this case we would make it visible when switching back to its view even if it was explicitely set to hidden...

I think this side effect problem is very less of a bug than the "not able to hide" bug.

**Comment by franckspike** [comment] 2015-02-12 21:39
Oh yes, I am using dual monitors at work and 3 monitors at home.

For 3 monitors, I set Windows to duplicate one, so it makes effectively 2 monitors.
But bug.n seems to use 3 monitors anyway, I did not spend more time on this yet...
With different resolutions, the Bar gets smaller than the screen too...

I also use two different keyboard settings, and bug.n often makes the setting not be the correct one. Just activating different windows and returning can make the keyboard setting change and alt-shift will change the systray icon but not the effective keyboard configuration.

**Comment by joten** [comment] 2015-02-17 19:55
> ProcessExplorer with "hide when minimized" option selected

This should work now. `KeePass` is another application, which has this option, and which I use myself -- although I circumvented the problem by simply moving the window to an otherwise empty view and therewith out of sight, too. The option "hide when minimized" includes in both cases "minimize when closed", therefor one has to exit the application to fully close it.

> Another window that does not close with win+c or alt+F4 is a file deletion confirmation dialog poped up by xplorer2 (a file explorer).

I only have access to the free version of xplorer², which uses the normal Windows Explorer dialog; this is a pop-up. Therefor I couldn't see any problems.

> should I write to @fuhsjr00 ?

Absolutely, though I thought, he would already have been involved in the conversation by the reference ( @fuhsjr00 ) (?).

> If we kept a list of the windows we hide due to view changes, ...

I now took a different approach to handling shell messages and active-window-tracking. It still needs some fine-tuning; could you test the current development version regarding xplorer² and file a bug report, if anything occurs?

> For 3 monitors, I set Windows to duplicate one, so it makes effectively 2 monitors. But bug.n seems to use 3 monitors anyway

I did a short test with two monitors, but bug.n only used one.

> With different resolutions, the Bar gets smaller than the screen too

Different resolutions?

If you can verify any of the above problems, please open a new issue. I will close this one -- not further hijacking it ;-)

**Closed by joten** 2015-02-17 19:55 UTC
Labels: bug
